name: Build WASM and deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build WASM library
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup GHC
        id: setup-haskell
        env:
          FLAVOUR: '9.12'
        run: |
          curl https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh
          ~/.ghc-wasm/add_to_github_path.sh

      - name: Dry run for cache key
        run: 'wasm32-wasi-cabal build exe:0315 --dry-run'

      - name: Cache
        uses: actions/cache@v4
        env:
          platform: wasm
        with:
          path: |
            ~/.ghc-wasm/.cabal/store
            dist-newstyle
          key: ${{ env.platform }}-${{ hashFiles('dist-newstyle/cache/plan.json') }}
          restore-keys: |
            ${{ env.platform }}-

      - name: Build
        run: './wasm/build.sh'

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4